branches:
  - main
  - name: dev
    prerelease: true
plugins:
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/git"
  - "@semantic-release/gitlab"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: echo v\${nextRelease.version} > nextVersion